CREATE TABLE USER
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME       VARCHAR(100) NOT NULL,
    TEL        VARCHAR(200) NOT NULL UNIQUE,
    ADDRESS    VARCHAR(100),
    CREATED_AT TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP    NOT NULL DEFAULT NOW(),
);